<a href="https://colab.research.google.com/github/ZeyadWaleed7/Numerical-Methods-MATH-307-/blob/main/LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.linalg  # Import SciPy's linear algebra module

def lu_decomposition(A):
    """Performs LU decomposition of a 3x3 matrix A."""

    n = A.shape[0]  # Get the size of the matrix (n=3 for a 3x3 matrix)

    # Step 1: Initialize matrices
    L = np.eye(n)  # Start L as an identity matrix
    U = np.zeros((n, n))  # Start U as a zero matrix

    # Step 2: Compute U (Upper Triangular)
    for i in range(n):
        for j in range(i, n):
            total = 0  # Reset sum
            for k in range(i):
                total += L[i, k] * U[k, j]  # Compute sum of previous multiplications
            U[i, j] = A[i, j] - total  # Assign the final value to U[i, j]

        # Step 3: Compute L (Lower Triangular)
        for j in range(i+1, n):
            total = 0  # Reset sum
            for k in range(i):
                total += L[j, k] * U[k, i]  # Compute sum of previous multiplications
            L[j, i] = (A[j, i] - total) / U[i, i]  # Assign the final value to L[j, i]

    return L, U  # Return the calculated matrices


# Define a 3x3 matrix
A = np.array([[2, -1, 1],
              [3, 3, 9],
              [3, 3, 5]], dtype=float)

# Perform LU decomposition (manual implementation)
L, U = lu_decomposition(A)

# Verify with SciPy's built-in LU function
P, L_scipy, U_scipy = scipy.linalg.lu(A)

# Print results
print("Original Matrix (A):\n", A)
print("\nManual LU Decomposition:")
print("Lower Triangular Matrix (L):\n", L)
print("Upper Triangular Matrix (U):\n", U)

# Verify A = LU using SciPy's inverse function
LU = np.dot(L, U)
print("\nReconstructed A (LU):\n", LU)
print("\nIs A equal to LU?", np.allclose(A, LU))  # Check if A and LU are almost equal

# Compare with SciPy's LU
print("\nSciPy's LU Decomposition:")
print("SciPy L:\n", L_scipy)
print("SciPy U:\n", U_scipy)


Original Matrix (A):
 [[ 2. -1.  1.]
 [ 3.  3.  9.]
 [ 3.  3.  5.]]

Manual LU Decomposition:
Lower Triangular Matrix (L):
 [[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
Upper Triangular Matrix (U):
 [[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]

Reconstructed A (LU):
 [[ 2. -1.  1.]
 [ 3.  3.  9.]
 [ 3.  3.  5.]]

Is A equal to LU? True

SciPy's LU Decomposition:
SciPy L:
 [[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]
SciPy U:
 [[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]
